### PR TITLE
refactor(workers): moved SQL to const

### PR DESCRIPTION
**Pull request by rittme**
Moved the id selecting SQL to it's own constant and removed useless duplicate query from insert SQL.

### CODE REVIEW

**Comment by oyiptong** [comment]
one thing to watch out for is that this query needs to occur in the same transaction as the insertion. Same goes with the previous version. I *think* (not sure, have to verify) that previously, it was executing in the same transaction.

Can you verify?

**Comment by rittme** [comment]
Previously the request was duplicate and the one with the insert was useless (I forgot to clean up the code there 😞). It seems Sqlite.jsm doesn't do multiple queries at the same statement (I'm not sure about that, but I couldn't get it to work). The request that is actually working is the [second one](https://github.com/mozilla/loci/blob/master/lib/task-queue/WorkerTask.js#L147).

From the SQLite documentation:

>  The [last_insert_rowid()](https://www.sqlite.org/lang_corefunc.html#last_insert_rowid) function returns the ROWID of the last row insert from the database connection which invoked the function.

Since every call to save() have it's own connection established, we should be fine.

Nevertheless, since I wrote this I've been thinking if we really need auto-incrementing ids for the tasks. Maybe it would be less overhead (and save us some I/O) to assign an id when we instantiate them? Something like you did at the [Task Processor](https://github.com/mozilla/loci/blob/master/lib/task-queue/TaskProcessor.js#L91).

**Comment by oyiptong** [comment]
great change then. But we also need to control the transactions. Can you look into sqlite.jsm to do so?

**Comment by oyiptong** [comment]
also, auto-incrementing ID's are the way to go :-)

**Pull request merged**
