### PR TITLE
Add LICENSE and basic README.md

### PR DESCRIPTION
**Pull request by pdehaan**
I'm reluctant to say this addresses the core #13 issue, since my README is woefully inadequate.

### CODE REVIEW

**Comment by oyiptong** [comment]
r+

**Comment by oyiptong** [comment]
closes #13 

It is better than what we have :-)

**Comment by pdehaan** [comment]
@oyiptong I have no self-merge powers here, so I may need a :hand: from you or @rittme now that Travis-CI is green.

**Comment by oyiptong** [comment]
@pdehaan go forth and be mergeful

**Pull request merged**
